feat(MF-46): configured db connection
Z1NGOD/MyFin-Back-End pull request #13
Opened 2024-04-21 20:59 UTC by Z1NGOD

2024-04-21 21:06 UTC, Sk3ll approved these changes

2024-04-21 21:07 UTC, Sk3ll requested changes

2024-04-21 21:07 UTC, Sk3ll commented on src/libs/db/configs/db.config.ts
delete empy file

2024-04-21 21:12 UTC, Z1NGOD commented on src/libs/db/configs/db.config.ts
did as was told

2024-04-21 21:13 UTC, Sk3ll approved these changes

2024-04-21 21:13 UTC, merged

2024-06-06 20:52 UTC, Z1NGOD commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/Z1NGOD/MyFin-Back-End/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: